services:
  # pihole:
  # image: pihole/pihole
  # ...
  pihole-sync:
    container_name: pihole-sync
    # image: TODO
    # network_mode: service:pihole
    build: .
    volumes:
      - ./config.json:/config.json
    environment:
      PIHOLE_API: http://pi.hole/api
      # May be empty (if no auth), or set to the application password
      PIHOLE_PASSWORD: ""
    restart: unless-stopped
